title: The Social Deck - Gov Design System Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: The Australian Government Design System as a theme
header:
  title: 2020 Review
  subtitle: Disability Standards for Education 2005
  has_nav: false
  nav_links:
    - label: Features
      url: /features
      style: link
    - label: Blog
      url: /blog
      style: link
    - label: About
      url: /about
      style: link
    - label: Style Guide
      url: /style-guide
      style: link
    - label: Contact Us
      url: /contact
      style: primary
  logo: images/header-logo-agov.png
footer:
  has_nav: true
  nav_links:
    - label: Contact Us
      url: /contact
      style: link
    - label: Privacy and Terms
      url: /terms
      style: link
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/'
      style: link
      new_window: true
    - label: GitHub
      url: 'https://github.com/'
      style: link
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: link
      new_window: true
  content: >-
    &copy; Commonwealth of Australia. With the exception of the Commonwealth
    Coat of Arms and where otherwise noted, this work is licensed under the <a
    href="https://github.com/govau/design-system-starter/blob/master/LICENSE"
    rel="external">MIT license</a>
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
subtitle: twertert
